version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'
